dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
dependencies:
  # - <organization/repo>@<version> from gitHub
  - smartcontractkit/chainlink-brownie-contracts@1.1.1 # to import chainLink in FundMe contract
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1" # map @chainLink
networks:
  default: development
  rinkeby:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: True
  mainnet-fork-dev2: # custom fork
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
  development:
    verify: False
  my-ganache-local:
    verify: False
